// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

const url = `sqlserver://${process.env.DB_HOST}:${process.env.DB_PORT};database=${process.env.DB_NAME};user=${process.env.DB_USER};password=${process.env.DB_PASS};trustServerCertificate=true`;

export default defineConfig({
  schema: "prisma/schema.prisma",
  datasource: {
    url,
  },
});
